version: '3.8'

services:
  db:
    image: postgres:14.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - .env

  web:
    build: .
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - .env

volumes:
  static_value:
  media_value:
 